import{a as q,s as S,i as B}from"./assets/vendor-CoJHoIDI.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const P="51378434-708cb4473fdf89ff203a412e8";async function f(o,e){return(await q("https://pixabay.com/api/",{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more-btn"),$=new S(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const e=o.map(({webformatURL:n,largeImageURL:l,tags:t,likes:r,views:s,comments:v,downloads:w})=>`<li class="gallery-item">
        <a class="gallery-link" href="${l}">
        <img
        class="gallery-image"
        src="${n}"
        alt="${t}"/>
        <div class="info-wrap">
        <p><span><b>Likes</b></span>${r}</p>
        <p><span><b>Views</b></span>${s}</p>
        <p><span><b>Comments</b></span>${v}</p>
        <p><span><b>Downloads</b></span>${w}</p>
        </div>
        </a>
    </li>`).join("");p.insertAdjacentHTML("beforeend",e),$.refresh()}function M(){p.innerHTML=""}function g(){m.classList.add("is-active")}function d(){m.classList.remove("is-active")}function b(){y.style.visibility="visible"}function u(){y.style.visibility="hidden"}const L=document.querySelector(".form"),H=L.querySelector("input"),O=document.querySelector(".load-more-btn");u();L.addEventListener("submit",x);let a=1,c="";O.addEventListener("click",C);async function x(o){if(o.preventDefault(),a=1,c=H.value.trim(),!c)return i("warning","Please enter a search query.");g(),M(),u();try{const e=await f(c,a);if(e.hits.length===0)return i("error","Sorry, there are no images matching your search query.");if(h(e.hits),e.totalHits>15&&b(),e.totalHits<=a*15)return i("info","You've reached the end of search results.")}catch{return i("error","Failed to fetch images. Please try again later.")}finally{d()}}async function C(){a++,u(),g();try{const o=await f(c,a);d(),h(o.hits);const e=document.querySelector(".gallery").firstElementChild;if(e){const{height:n}=e.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}if(o.totalHits<=a*15){i("info","You've reached the end of search results."),setTimeout(()=>{u()},1e3);return}else b()}catch{return i("error","Failed to load more images. Please check your connection or try again.")}finally{d()}}function i(o,e){B[o]({message:e,position:"topRight",backgroundColor:"#ef4040",messageColor:"#ffffff",maxWidth:432})}
//# sourceMappingURL=index.js.map
