import{a as q,s as S,i as B}from"./assets/vendor-CoJHoIDI.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const P="51378434-708cb4473fdf89ff203a412e8";async function p(o,e){return(await q("https://pixabay.com/api/",{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),$=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const e=o.map(({webformatURL:n,largeImageURL:l,tags:t,likes:r,views:a,comments:v,downloads:w})=>`<li class="gallery-item">
        <a class="gallery-link" href="${l}">
        <img
        class="gallery-image"
        src="${n}"
        alt="${t}"/>
        <div class="info-wrap">
        <p><span><b>Likes</b></span>${r}</p>
        <p><span><b>Views</b></span>${a}</p>
        <p><span><b>Comments</b></span>${v}</p>
        <p><span><b>Downloads</b></span>${w}</p>
        </div>
        </a>
    </li>`).join("");m.insertAdjacentHTML("beforeend",e),$.refresh()}function M(){m.innerHTML=""}function b(){y.classList.add("is-active")}function u(){y.classList.remove("is-active")}function L(){h.style.visibility="visible"}function d(){h.style.visibility="hidden"}const f=document.querySelector(".form"),x=f.querySelector("input"),O=document.querySelector(".load-more-btn");d();f.addEventListener("submit",C);let i=1,c="";O.addEventListener("click",E);async function C(o){if(o.preventDefault(),i=1,c=x.value.trim(),!c)return s("warning","Please enter a search query.");b(),M(),d();try{const e=await p(c,i);if(u(),e.hits.length===0)return s("error","Sorry, there are no images matching your search query.");g(e.hits),e.totalHits>15&&L(),f.elements["search-text"].value=""}catch{return s("error","Failed to fetch images. Please try again later.")}finally{u()}}async function E(){i++,d(),b();try{const o=await p(c,i);u(),g(o.hits);const e=document.querySelector(".gallery").firstElementChild;if(e){const{height:n}=e.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"})}if(o.totalHits<=i*15)return d(),s("info","You've reached the end of search results.");L()}catch{return s("error","Failed to load more images. Please check your connection or try again.")}finally{u()}}function s(o,e){B[o]({message:e,position:"topRight",backgroundColor:"#ef4040",messageColor:"#ffffff",maxWidth:432})}
//# sourceMappingURL=index.js.map
